
setting.style.display ="block"
beep.style.display ="block"

score_10000.style.display ="block"
score_10000_a.style.display ="block"
score_10000_b.style.display ="block"
score_10000_c.style.display ="block"
score_10000_d.style.display ="block"
score_10000_e.style.display ="block"
score_10000_f.style.display ="block"
score_10000_g.style.display ="block"

score_1000.style.display ="block"
score_1000_a.style.display ="block"
score_1000_b.style.display ="block"
score_1000_c.style.display ="block"
score_1000_d.style.display ="block"
score_1000_e.style.display ="block"
score_1000_f.style.display ="block"
score_1000_g.style.display ="block"

score_100.style.display ="block"
score_100_a.style.display ="block"
score_100_b.style.display ="block"
score_100_c.style.display ="block"
score_100_d.style.display ="block"
score_100_e.style.display ="block"
score_100_f.style.display ="block"
score_100_g.style.display ="block"

score_10.style.display ="block"
score_10_a.style.display ="block"
score_10_b.style.display ="block"
score_10_c.style.display ="block"
score_10_d.style.display ="block"
score_10_e.style.display ="block"
score_10_f.style.display ="block"
score_10_g.style.display ="block"

score_1.style.display ="block"
score_1_a.style.display ="block"
score_1_b.style.display ="block"
score_1_c.style.display ="block"
score_1_d.style.display ="block"
score_1_e.style.display ="block"
score_1_f.style.display ="block"
score_1_g.style.display ="block"